<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <DalamudLibPath Condition="'$(DalamudLibPath)' == ''">$(APPDATA)\XIVLauncher\addon\Hooks\dev\</DalamudLibPath>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Platforms>x64</Platforms>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <OutputPath>$(APPDATA)\XIVLauncher\devPlugins\BSTExtra\</OutputPath>
    <AssemblyName>BSTExtra</AssemblyName>
    <RootNamespace>BSTExtra</RootNamespace>
    <Version>1.0.2</Version>
    <Description>Adds BST Extra rotation to Rotation Solver Reborn.</Description>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="BST_Extra.cs" />
    <None Include="BSTExtra.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Dalamud">
      <HintPath>$(DalamudLibPath)Dalamud.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
